
string  TYPE_REMAIN_DIST_AFTER_CLEAN     = "RemainDistAfterClean"              #结束清洁，集水继续行驶距离
string  TYPE_ROLL_BRUSH_DELAY_TIME       = "RollBrushDelayTime"                #滚刷延时抬起时间
string  TYPE_ROLL_BRUSH_THROW_WATER_TIME = "RollBrushThrowWaterTime"           #滚刷甩水保持时间
string  TYPE_CLEAN_FINISH_SUCTION_POWER  = "CleanFinishSuctionPower"           #吸风电机收尾时吸风功率(转速)
string  TYPE_SQUEEGEE_REMAIN_TIME        = "SqueegeeRemainTime"                #吸水扒保持实际
string  TYPE_DELAY_SUCTION_REMAIN_TIME   = "DelaySuctionRemainTime"            #延迟吸风保持时间
string  TYPE_NO_MOVE_TIMEOUT             = "NoMoveTimeout"                     #未运动超时提醒时间
string  TYPE_SELF_CLEAN_CYCLES_NUM       = "SelfCleanCyclesNumber"             #自清洁循环冲洗次数

string  config_type    # 参数配置类型
float32 value          # 对应的具体数值