# Provide Develop mode configuration service
# service name: /config_develop_mode

uint32 UPDATE = 0             # 更新
uint32 GET = 1                # 获取
uint32 RESET = 2              # 重置

uint32 cmd                     # 命令类型（必填）
DevModeConf  config_info         # 参数配置信息
---
uint32 result                   # 返回结果（必填）
DevModeConf[] config_infos      # 所有配置参数信息