name: generate binary
on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yunxianhua/ros2_ws/ros2-x86-runner:latest
    permissions:
      packages: write
      contents: read
    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: generate
        run: |
          pwd
          ls -larth
          /usr/bin/git config --global --add safe.directory /__w/ros2_ws/ros2_ws
          /ros_entrypoint.sh colcon build

      - name: zip-artifact
        run: zip -r install.zip install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: install
          path: install.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: install.zip