name: generate binary
on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/YunxianHua/ros2_ws/ros2-x86-runner:latest
    permissions:
      packages: write
      contents: read
    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: generate
        run: colcon build
      - name: zip-artifact
        run: zip -r install.zip install
      - name: Cache jvmJar
        uses: actions/upload-artifact@v3
        with:
          name: semanticLibJar
          path: |
            build/libs/semantic-lib.jar
          retention-days: 2
  publish-image-to-azure:
    needs: build
    runs-on: ubuntu-latest
    environment: azure-dev-east-us
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact semanticLibJar
        uses: actions/download-artifact@v3
        with:
          name: semanticLibJar
          path: build/libs/semantic-lib.jar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: ACR login
        uses: docker/login-action@v2
        with:
          registry: coseus.azurecr.io
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.workflow
          tags: |
            coseus.azurecr.io/semantic-binary:${{ github.ref_name }}
            coseus.azurecr.io/semantic-binary:latest
          push: true
  copy-image-to-aliyun:
    needs:
      - publish-image-to-azure
    uses: coscene-io/cicd-templates/.github/workflows/cp-image-to-aliyun.yml@main
    with:
      project: semantic-binary
      tag: ${{ github.ref_name }}
    secrets: inherit
