name: generate binary
on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        arch: [ x86_64, arm64 ]
        include:
          - arch: x86_64
            os: linux
            label: ubuntu-latest
          - arch: arm64
            os: linux
            label: [ aliyun, arm ]
    runs-on: ${{ matrix.label }}
    container: ghcr.io/yunxianhua/ros2_ws/ros2-foxy-runner:latest
    permissions:
      contents: write

    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      GH_PACKAGES_ORG_TOKEN: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: generate
        run: |
          pwd
          ls -larth
          /usr/bin/git config --global --add safe.directory /__w/ros2_ws/ros2_ws
          /ros_entrypoint.sh colcon build

      - name: zip-artifact
        run: zip -r install.zip install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ros2_ws
          path: install.zip
